# Generated by Django 5.0.14 on 2026-06-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubes', '0002_alter_cubecard_section'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statquery',
            name='cube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat_queries', to='cubes.cube'),
        ),
    ]
