# Generated by Django 5.0.14 on 2026-07-04 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_clean_non_english_printed_fallbacks'),
        ('stats', '0002_statquery_cube'),
    ]

    operations = [
        migrations.AddField(
            model_name='statquery',
            name='match_cache_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StatQueryDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='stats.statquery')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='stats.statquery')),
            ],
        ),
        migrations.CreateModel(
            name='StatQueryMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('oracle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_query_matches', to='cards.cardoracle')),
                ('stat_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='stats.statquery')),
            ],
        ),
        migrations.AddConstraint(
            model_name='statquerydependency',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='unique_stat_query_dependency'),
        ),
        migrations.AddConstraint(
            model_name='statquerymatch',
            constraint=models.UniqueConstraint(fields=('stat_query', 'oracle'), name='unique_stat_query_oracle_match'),
        ),
    ]
