# Generated by Django 5.0.14 on 2026-07-04 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_clean_non_english_printed_fallbacks'),
        ('stats', '0003_statquery_match_cache_refreshed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetIndicatorExpectedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_key', models.CharField(max_length=64)),
                ('expected', models.FloatField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_expected_values', to='cards.set')),
                ('stat_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.statquery')),
            ],
        ),
        migrations.AddConstraint(
            model_name='setindicatorexpectedvalue',
            constraint=models.UniqueConstraint(fields=('set', 'indicator_key', 'stat_query'), name='unique_set_indicator_expected_value', nulls_distinct=False),
        ),
    ]
