# Generated by Django 5.0.14 on 2026-06-18 14:32

from django.db import migrations, models


def blank_sections_to_main(apps, schema_editor):
    CubeCard = apps.get_model('cubes', 'CubeCard')
    CubeCard.objects.filter(section='').update(section='main')


class Migration(migrations.Migration):

    dependencies = [
        ('cubes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(blank_sections_to_main, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cubecard',
            name='section',
            field=models.CharField(choices=[('main', 'Main'), ('maybeboard', 'Maybeboard'), ('sideboard', 'Sideboard'), ('tokens', 'Tokens'), ('utility', 'Utility'), ('archive', 'Archive')], default='main', max_length=64),
        ),
    ]
