# Generated by Django 5.0.14 on 2026-06-17 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardOracle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scryfall_oracle_id', models.UUIDField(unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('mana_cost', models.CharField(blank=True, max_length=255)),
                ('mana_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('color_identity', models.JSONField(blank=True, default=list)),
                ('type_line', models.CharField(blank=True, db_index=True, max_length=255)),
                ('oracle_text', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('power', models.CharField(blank=True, max_length=16)),
                ('toughness', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('released_at', models.DateField(blank=True, null=True)),
                ('set_type', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-released_at', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CardPrinting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scryfall_id', models.UUIDField(unique=True)),
                ('set_code', models.CharField(db_index=True, max_length=16)),
                ('collector_number', models.CharField(max_length=32)),
                ('rarity', models.CharField(blank=True, max_length=32)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('released_at', models.DateField(blank=True, null=True)),
                ('lang', models.CharField(db_index=True, default='en', max_length=16)),
                ('oracle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printings', to='cards.cardoracle')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printings', to='cards.set')),
            ],
            options={
                'ordering': ['oracle__name', '-released_at', 'set_code', 'collector_number'],
                'indexes': [models.Index(fields=['set_code', 'collector_number'], name='cards_cardp_set_cod_21c087_idx')],
            },
        ),
    ]
