# Generated by Django 5.0.14 on 2026-06-18 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_cardoracle_mana_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField()),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='cards.set')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['set__code'],
            },
        ),
        migrations.AddConstraint(
            model_name='usersetpreference',
            constraint=models.UniqueConstraint(fields=('user', 'set'), name='unique_user_set_preference'),
        ),
    ]
