# Generated by Django 5.0.14 on 2026-06-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_usersetpreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardprinting',
            name='printed_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cardprinting',
            name='printed_oracle_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cardprinting',
            name='printed_type_line',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
