# Generated by Django 5.0.14 on 2026-06-18 18:03

from django.db import migrations


def clean_non_english_printed_fallbacks(apps, schema_editor):
    CardPrinting = apps.get_model("cards", "CardPrinting")
    for printing in CardPrinting.objects.exclude(lang="en").select_related("oracle").iterator():
        update_fields = []
        if printing.printed_name == printing.oracle.name:
            printing.printed_name = ""
            update_fields.append("printed_name")
        if printing.printed_type_line == printing.oracle.type_line:
            printing.printed_type_line = ""
            update_fields.append("printed_type_line")
        if printing.printed_oracle_text == printing.oracle.oracle_text:
            printing.printed_oracle_text = ""
            update_fields.append("printed_oracle_text")
        if update_fields:
            printing.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_cardprinting_printed_name_and_more"),
    ]

    operations = [
        migrations.RunPython(clean_non_english_printed_fallbacks, migrations.RunPython.noop),
    ]
